# Configuraci칩n de WGEF2
flags:
  enabled:
    - no-elytra
    - anti-enderman-grief
    - block-piston-transloc

# Actualizaciones autom치ticas
auto-update: true

# Mensajes
messages:
  no-permission: "&cNo tienes permiso para hacer esto!"
  flag-denied: "&cAcci칩n denegada en esta 치rea"